#!/bin/bash
set -euo pipefail
IFS=$' \n\t'
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

make config=debug_linux -j12
./check
echo "==== build done ===="
./bin/Debug-Linux/lynton/lynton
