# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_wasm
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_wasm)
  lynton_config = debug_wasm

else ifeq ($(config),debug_linux)
  lynton_config = debug_linux

else ifeq ($(config),debug_windows)
  lynton_config = debug_windows

else ifeq ($(config),release_wasm)
  lynton_config = release_wasm

else ifeq ($(config),release_linux)
  lynton_config = release_linux

else ifeq ($(config),release_windows)
  lynton_config = release_windows

else ifeq ($(config),dist_wasm)
  lynton_config = dist_wasm

else ifeq ($(config),dist_linux)
  lynton_config = dist_linux

else ifeq ($(config),dist_windows)
  lynton_config = dist_windows

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := lynton

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

lynton:
ifneq (,$(lynton_config))
	@echo "==== Building lynton ($(lynton_config)) ===="
	@${MAKE} --no-print-directory -C lynton -f Makefile config=$(lynton_config)
endif

clean:
	@${MAKE} --no-print-directory -C lynton -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_wasm"
	@echo "  debug_linux"
	@echo "  debug_windows"
	@echo "  release_wasm"
	@echo "  release_linux"
	@echo "  release_windows"
	@echo "  dist_wasm"
	@echo "  dist_linux"
	@echo "  dist_windows"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   lynton"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"